#!/usr/bin/env bash
#  a Bash script that configures a new Ubuntu machine
# Install nginx on me web-01 server, Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request
#  (requesting a page) using curl,
#  it must return a page that contains the string Hello World!

sudo apt-get -y update
sudo apt-get -y Install nginx
sudo ufw 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
