#!/usr/bin/env bash
# Configure your Nginx server for 404

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Ceci n'"'"'est pas une page' | sudo tee /usr/share/nginx/html/404.html

echo "Holberton School" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo sed -i "error_page 404 /404.html;\n\t
    location = /404.html {
		root /usr/share/nginx/html;\n\t
        internal;\n\t
    }" /usr/share/nginx/html

sudo service nginx restart
