#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install haproxy
echo "frontend  jawad-frontend
        bind *:80
        mode http
        default_backend jawad-backend
backend jawad-backend
        balance roundrobin
        server web-01 54.160.95.196:80 check
        server web-02 54.90.35.241:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
