#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01.
# Configure ufw so that it blocks all incoming traffic,
# except the following TCP ports: 22 (SSH) 443 (HTTPS SSL) 80 (HTTP)

echo -e "Updating de apt\n"
sudo apt-get update
echo -e "Installing ufw"
sudo apt-get -y install ufw
echo -e "Configuration ufw to the default inoming and outgoing"
sudo ufw default deny incoming
sudo ufw default allow outgoing
echo -e "allow 22/tcp 443/tcp 80/tcp"
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
echo -e "enable ufw"
sudo ufw enable
echo -e "status ufw"
sudo ufw status
